"""PDK-free tests for the shared thermal trip-search helpers (issue #297)."""

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path

SIM = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SIM / "bin"))
import _record_common as rc  # noqa: E402


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class FakePdk:
    lib_file = "/fake/sky130.lib.spice"


BODY = ["R1 a b 1k", "C1 b 0 1p"]

# Golden strings captured from the PRE-refactor deck_text() implementations.
GOLDEN_HYST = (
    "* thermal hysteresis (integrated LDO) demonstration deck -- generated by run_hysteresis.py, do not edit\n"
    "* corner: tt / 3.3 V / 27.5 C\n.param vsup=3.3\n.param ix_amp=5e-07\n.param en_dip=0\n"
    ".option wnflag=1\n.temp 27.5\n.lib \"/fake/sky130.lib.spice\" tt\nR1 a b 1k\nC1 b 0 1p\n"
    ".control\nsave all\ntran 400n 170u uic\n"
    "wrdata /tmp/x.dat v(xldo.ts_cmp) v(xldo.rc_a) v(xldo.rc_b) v(xldo.ea_out) v(vout) v(en) "
    "v(xldo.ts_sns) v(xldo.ts_ref)\nquit\n.endc\n.end\n"
)
GOLDEN_DEMO = (
    "* thermal-regen-cmp demonstration deck -- generated by run_demo.py, do not edit\n"
    "* corner: tt / 3.3 V / 27.5 C\n.param vsup=3.3\n.param vx_amp=-0.25\n.param en_dip=0\n"
    ".temp 27.5\n.lib \"/fake/sky130.lib.spice\" tt\nR1 a b 1k\nC1 b 0 1p\n"
    ".control\nsave all\ntran 400n 110u uic\n"
    "wrdata /tmp/x.dat v(ts_cmp) v(xcmp.rc_a) v(xcmp.rc_b) v(ea_stub) v(en) v(ts_sns) v(ts_ref)\n"
    "quit\n.endc\n.end\n"
)


class TestAt(unittest.TestCase):
    T = [0.0, 1e-6, 2e-6, 4e-6]
    Y = [10, 11, 12, 14]

    def test_exact(self):
        self.assertEqual(rc.at(self.T, self.Y, 2), 12)

    def test_nearest_both_sides_no_interpolation(self):
        self.assertEqual(rc.at(self.T, self.Y, 1.2), 11)
        self.assertEqual(rc.at(self.T, self.Y, 1.8), 12)

    def test_tie_first_index(self):
        self.assertEqual(rc.at([0.0, 2e-6, 4e-6], [7, 8, 9], 1), 7)
        self.assertEqual(rc.at([0.0, 2e-6], [1, 2], 1), 1)

    def test_out_of_range_endpoints(self):
        self.assertEqual(rc.at(self.T, self.Y, -5), 10)
        self.assertEqual(rc.at(self.T, self.Y, 99), 14)


class TestTripped(unittest.TestCase):
    def test_threshold(self):
        for sup in (3.3, 1.8):
            self.assertTrue(rc.tripped(sup / 2 - 0.01, sup))
            self.assertFalse(rc.tripped(sup / 2, sup))
            self.assertFalse(rc.tripped(sup / 2 + 0.01, sup))


class TestBisect(unittest.TestCase):
    def test_want_lowest(self):
        lo, hi = rc.bisect(lambda x: x >= 37.0, 0.0, 100.0, 0.5, True)
        self.assertLessEqual(hi - lo, 0.5)
        self.assertLess(lo, 37.0)
        self.assertGreaterEqual(hi, 37.0)

    def test_want_highest(self):
        lo, hi = rc.bisect(lambda x: x <= 37.0, 0.0, 100.0, 0.5, False)
        self.assertLessEqual(hi - lo, 0.5)
        self.assertLessEqual(lo, 37.0)
        self.assertGreater(hi, 37.0)

    def test_exact_bracket_sequence(self):
        self.assertEqual(rc.bisect(lambda x: x >= 40, 0.0, 100.0, 25.0, True), (25.0, 50.0))
        self.assertEqual(rc.bisect(lambda x: x <= 40, 0.0, 100.0, 25.0, False), (25.0, 50.0))

    def test_no_evaluation_when_within_tol(self):
        self.assertEqual(rc.bisect(lambda x: x >= 5, 0.0, 10.0, 10.0, True), (0.0, 10.0))

    def test_invalid_brackets(self):
        with self.assertRaises(AssertionError):  # hi fails
            rc.bisect(lambda x: x >= 200, 0.0, 100.0, 1.0, True)
        with self.assertRaises(AssertionError):  # lo already satisfies
            rc.bisect(lambda x: x >= -1, 0.0, 100.0, 1.0, True)
        with self.assertRaises(AssertionError):  # lo fails
            rc.bisect(lambda x: x <= -1, 0.0, 100.0, 1.0, False)
        with self.assertRaises(AssertionError):  # hi already satisfies
            rc.bisect(lambda x: x <= 200, 0.0, 100.0, 1.0, False)


class TestReadDat(unittest.TestCase):
    def _read(self, rows, names):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "x.dat"
            p.write_text(rows)
            return rc.read_dat(p, names)

    def test_eight_names(self):
        names = ["ts_cmp", "rc_a", "rc_b", "ea_out", "vout", "en", "ts_sns", "ts_ref"]
        r1 = " ".join(f"0 {i + 1}" for i in range(8))
        r2 = " ".join(f"1e-6 {i + 11}" for i in range(8))
        t, v = self._read(f"{r1}\n\n{r2}\n", names)
        self.assertEqual(t, [0.0, 1e-6])
        self.assertEqual(v, {n: [float(i + 1), float(i + 11)] for i, n in enumerate(names)})

    def test_seven_names(self):
        names = ["ts_cmp", "rc_a", "rc_b", "ea_stub", "en", "ts_sns", "ts_ref"]
        r1 = " ".join(f"0 {i + 1}" for i in range(7))
        r2 = " ".join(f"2e-6 {i + 21}" for i in range(7))
        t, v = self._read(f"{r1}\n{r2}\n", names)
        self.assertEqual(t, [0.0, 2e-6])
        self.assertEqual(v, {n: [float(i + 1), float(i + 21)] for i, n in enumerate(names)})


class TestRunnerWiring(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.hyst = load("run_hysteresis", SIM / "thermal" / "run_hysteresis.py")
        cls.demo = load("run_demo", SIM / "thermal-regen-cmp" / "run_demo.py")

    def test_no_local_copies(self):
        for m in (self.hyst, self.demo):
            for fn in ("read_dat", "at", "tripped", "bisect"):
                self.assertIs(getattr(m, fn), getattr(rc, fn))

    def test_vector_schemas(self):
        self.assertEqual(self.hyst.KEYS, ["ts_cmp", "rc_a", "rc_b", "ea_out", "vout", "en", "ts_sns", "ts_ref"])
        self.assertEqual(self.demo.KEYS, ["ts_cmp", "rc_a", "rc_b", "ea_stub", "en", "ts_sns", "ts_ref"])

    def test_deck_text_golden(self):
        self.assertEqual(self.hyst.deck_text(BODY, FakePdk(), 27.5, 0.5e-6, "0", "/tmp/x.dat"), GOLDEN_HYST)
        self.assertEqual(self.demo.deck_text(BODY, FakePdk(), 27.5, -0.25, "0", "/tmp/x.dat"), GOLDEN_DEMO)


if __name__ == "__main__":
    unittest.main()
