#!/usr/bin/env python3
"""Bounded tt/3.30 V single-corner trip/reset hysteresis demonstration of the
INTEGRATED LDO (design/ldo_3v3in_1v8out.sch with the regenerative thermal
comparator, issue #230; parent #131).

DEVELOPMENT EVIDENCE ONLY.  One process corner (tt), one supply (3.30 V), one
temperature axis walked as a staircase of *separate* transient runs (ngspice
has no time-varying TEMP; a `dc temp` continuation cannot discriminate the two
branches -- sim/README.md #189).  NOT PVT qualification and NOT a proof of
DR-005's >= 150 C worst-corner trip floor.

Bench: sim/thermal/testbench/tb_thermal_trip.sch (the real LDO, C_OUT, R_LOAD);
IX is a removable physical disturbance current at the sense node xldo.TS_SNS.

  cold        EN rises from 0 with every node at 0 (`uic`): the latch starts
              from the symmetric EN=0 state and resolves on the input sign.
  hot         EN high; a +ix sink on TS_SNS (sense looks hotter) 20..40 us,
              then REMOVED; observed at 90 us: is the TRIPPED state held with
              zero disturbance at this temperature?  -> T_reset
  cold_exc    the same with -ix (sense looks colder): is the UNTRIPPED state
              held?  -> T_trip
  en          `hot`, then EN dropped 101..115 us and re-enabled; observe
              TS_CMP/M_TSHUT while EN low and the state after the re-enable.

T_reset (falling) = lowest T at which the tripped state is still held;
T_trip (rising) = highest T at which the untripped state is still held; both by
a 10 C coarse grid then bisection.  Hysteresis = T_trip - T_reset.
Runs execute strictly serially (no pools, no background jobs, no corner/MC
grid): host rules for the shared worker.

Usage:
  python3 sim/thermal/run_hysteresis.py [--out DIR] [--tag TAG]
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
sys.path.insert(0, str(REPO_ROOT / "sim" / "bin"))
from _record_common import at, bisect, load_corner_run_module, read_dat, tripped  # noqa: E402

cr = load_corner_run_module(REPO_ROOT / "sim" / "bin")

SCHEMATIC = HERE / "testbench" / "tb_thermal_trip.sch"
VSUP = 3.30
PROCESS = "tt"
T_STOP_US = 170
TSTEP = "400n"
# observation instants (us): end of cold start / during disturbance / hold after
# release / EN low / after EN re-enable
T_COLD, T_FORCED, T_HOLD, T_EN_LOW, T_REEN = 19, 39, 90, 108, 165
PROGRESS_RE = re.compile(r"\s*Reference value :\s*[-+0-9.eE]+")
EXTRA_MARKERS = ("source stepping failed", "timestep too small", "Transient op", "Error:")
IX_HOT, IX_COLD = +0.5e-6, -0.5e-6  # sink on TS_SNS (hotter) / injection (colder), amperes
VECTORS = ["xldo.ts_cmp", "xldo.rc_a", "xldo.rc_b", "xldo.ea_out", "vout", "en", "xldo.ts_sns", "xldo.ts_ref"]
KEYS = ["ts_cmp", "rc_a", "rc_b", "ea_out", "vout", "en", "ts_sns", "ts_ref"]


eval_xschem_exprs = cr.eval_xschem_exprs


def deck_text(netlist_body: list[str], pdk, temp_c: float, ix_amp: float, en_dip: str, dat: str) -> str:
    head = [
        "* thermal hysteresis (integrated LDO) demonstration deck -- generated by run_hysteresis.py, do not edit",
        f"* corner: {PROCESS} / {VSUP} V / {temp_c} C",
        f".param vsup={VSUP}",
        f".param ix_amp={ix_amp}",
        f".param en_dip={en_dip}",
        ".option wnflag=1",
        f".temp {temp_c}",
        f'.lib "{pdk.lib_file}" {PROCESS}',
    ]
    ctl = [
        ".control",
        "save all",
        f"tran {TSTEP} {T_STOP_US}u uic",
        f"wrdata {dat} " + " ".join(f"v({v})" for v in VECTORS),
        "quit",
        ".endc",
        ".end",
        "",
    ]
    return "\n".join(head + netlist_body + ctl)


class Runner:
    def __init__(self, out: Path, pdk, body):
        self.out, self.pdk, self.body = out, pdk, body
        self.n = 0
        self.runs: list[dict] = []
        self.work = Path(tempfile.mkdtemp(prefix="thermal-hyst-"))
        shutil.copy(REPO_ROOT / "sim" / "spiceinit", self.work / ".spiceinit")
        (out / "runs").mkdir(parents=True, exist_ok=True)

    def run(self, scenario: str, temp_c: float, ix_amp: float = 0.0, en_dip: str = "vsup") -> dict:
        self.n += 1
        rid = f"{self.n:03d}_{scenario}_{temp_c:g}C" + (f"_ix{ix_amp*1e6:+g}uA" if ix_amp else "")
        dat = self.work / f"{rid}.dat"
        deck = self.work / f"{rid}.cir"
        deck.write_text(deck_text(self.body, self.pdk, temp_c, ix_amp, en_dip, str(dat)))
        proc = subprocess.run(
            ["ngspice", "-b", str(deck)],
            cwd=self.work, capture_output=True, text=True, timeout=900, stdin=subprocess.DEVNULL,
        )
        raw = (proc.stdout + "\n" + proc.stderr).replace("\r", "\n")
        log = "\n".join(ln for ln in (PROGRESS_RE.sub("", x).rstrip() for x in raw.splitlines())
                        if ln and not ln.startswith("option SCALE"))
        diag = cr.detect_solver_diagnostic(log) or next(
            (ln.strip() for ln in log.splitlines() if any(m in ln for m in EXTRA_MARKERS)), None
        )
        if not dat.is_file():
            raise RuntimeError(f"{rid}: ngspice produced no data (rc={proc.returncode})\n{log[-800:]}")
        t, v = read_dat(dat, KEYS)
        c = lambda k, x: round(at(t, v[k], x), 4)  # noqa: E731
        res = {
            "id": rid, "scenario": scenario, "temp_c": temp_c, "ix_amp_a": ix_amp, "en_dip": en_dip,
            "ngspice_rc": proc.returncode, "solver_diagnostic": diag,
            "cold_start_tripped": tripped(at(t, v["ts_cmp"], T_COLD), VSUP),
            "forced_tripped": tripped(at(t, v["ts_cmp"], T_FORCED), VSUP),
            "hold_tripped": tripped(at(t, v["ts_cmp"], T_HOLD), VSUP),
            "ts_cmp_v": {k: c("ts_cmp", k) for k in (T_COLD, T_FORCED, T_HOLD, T_EN_LOW, T_REEN)},
            "m_tshut_vsg_v": {k: round(VSUP - at(t, v["ts_cmp"], k), 4) for k in (T_COLD, T_FORCED, T_HOLD, T_REEN)},
            "ea_out_v": {k: c("ea_out", k) for k in (T_COLD, T_FORCED, T_HOLD, T_REEN)},
            "vout_v": {k: c("vout", k) for k in (T_COLD, T_FORCED, T_HOLD, T_REEN)},
            "rc_a_v": {k: c("rc_a", k) for k in (T_COLD, T_HOLD, T_REEN)},
            "rc_b_v": {k: c("rc_b", k) for k in (T_COLD, T_HOLD, T_REEN)},
            "sns_minus_ref_mv_at_hold": round(1e3 * (at(t, v["ts_sns"], T_HOLD) - at(t, v["ts_ref"], T_HOLD)), 2),
            "after_en_reenable_tripped": tripped(at(t, v["ts_cmp"], T_REEN), VSUP),
            "ts_cmp_while_en_low_v": c("ts_cmp", T_EN_LOW),
            "en_while_low_v": c("en", T_EN_LOW),
        }
        (self.out / "runs" / f"{rid}.log").write_text(log + "\n")
        with (self.out / "runs" / f"{rid}.csv").open("w") as f:
            f.write("t_us," + ",".join(KEYS) + "\n")
            for i in range(0, len(t), max(1, len(t) // 260)):
                f.write(f"{t[i]*1e6:.3f}," + ",".join(f"{v[k][i]:.5f}" for k in KEYS) + "\n")
        self.runs.append(res)
        print(f"  {rid}: forced={'T' if res['forced_tripped'] else 'u'} hold={'T' if res['hold_tripped'] else 'u'}"
              f" cold={'T' if res['cold_start_tripped'] else 'u'} diag={diag}", flush=True)
        return res

    # ---- monotone hold predicates -------------------------------------
    def tripped_held(self, temp, amp=IX_HOT):
        r = self.run("hot", temp, amp)
        return r["forced_tripped"] and r["hold_tripped"]

    def untripped_held(self, temp, amp=IX_COLD):
        r = self.run("cold_exc", temp, amp)
        return (not r["forced_tripped"]) and (not r["hold_tripped"])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--tag", default="")
    ap.add_argument("--tol", type=float, default=0.3125, help="bisection bracket width (C)")
    args = ap.parse_args()

    pdk = cr.resolve_pdk(cr.load_pin())
    git = cr.git_state()
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d-%H%M%S")
    rec_id = f"{stamp}-{git['sha']}" + (f"-{args.tag}" if args.tag else "")
    out = args.out or (HERE / "hysteresis" / rec_id)
    out.mkdir(parents=True, exist_ok=False)  # append-only: never reuse a record directory

    with tempfile.TemporaryDirectory(prefix="thermal-hyst-nl-") as nl:
        net = cr.netlist_with_xschem(SCHEMATIC, Path(nl), pdk)
        text, n_expr = eval_xschem_exprs("\n".join(cr.netlist_body(net, eval_exprs=False)) + "\n")
        # The bench's IC_SEED `.nodeset` card seeds the `dc temp` sweeps (#178/#189).
        # ngspice 42 also honours it as an initial condition under `tran ... uic`
        # (it pre-charged VOUT to 1.8 V in the first draft), which would make the
        # "cold start" a seeded one.  Drop it here so every node starts at 0.
        stmts = [x for x in re.split(r"\n(?!\+)", text.rstrip("\n")) if not x.lower().startswith(".nodeset")]
        body = "\n".join(stmts).split("\n")
        (out / "netlist.spice").write_text("\n".join(body) + "\n")

    r = Runner(out, pdk, body)
    print(f"record {rec_id}: tt / {VSUP} V, bisection tol {args.tol} C, expr() substitutions {n_expr}", flush=True)

    print("[1] coarse bracket (10 C grid)", flush=True)
    grid = [130, 140, 150, 160, 170, 180, 190]
    held_t = {T: r.tripped_held(T) for T in grid}
    held_u = {T: r.untripped_held(T) for T in grid}
    t_lo_reset = max(T for T in grid if not held_t[T] and all(not held_t[x] for x in grid if x <= T))
    t_hi_reset = min(T for T in grid if held_t[T] and T > t_lo_reset)
    t_lo_trip = max(T for T in grid if held_u[T] and all(held_u[x] for x in grid if x <= T))
    t_hi_trip = min(T for T in grid if not held_u[T] and T > t_lo_trip)

    print("[2] bisect T_reset (falling) and T_trip (rising)", flush=True)
    reset_lo, reset_hi = bisect(r.tripped_held, t_lo_reset, t_hi_reset, args.tol, True)
    trip_lo, trip_hi = bisect(r.untripped_held, t_lo_trip, t_hi_trip, args.tol, False)
    reset_mid, trip_mid = (reset_lo + reset_hi) / 2, (trip_lo + trip_hi) / 2

    print("[3] disturbance-amplitude robustness at the flip points", flush=True)
    robust = {}
    for amp in (0.25e-6, 1.0e-6):
        robust[f"tripped_held_{amp*1e6:+g}uA_at_{reset_hi:g}C"] = r.tripped_held(reset_hi, amp)
        robust[f"tripped_held_{amp*1e6:+g}uA_at_{reset_lo:g}C"] = r.tripped_held(reset_lo, amp)
    for amp in (-0.25e-6, -1.0e-6):
        robust[f"untripped_held_{amp*1e6:+g}uA_at_{trip_lo:g}C"] = r.untripped_held(trip_lo, amp)
        robust[f"untripped_held_{amp*1e6:+g}uA_at_{trip_hi:g}C"] = r.untripped_held(trip_hi, amp)

    print("[4] cold start and EN disable/re-enable inside and outside the window", flush=True)
    pts = sorted({round(x) for x in (reset_mid - 8, reset_mid - 1, reset_mid + 2, (reset_mid + trip_mid) / 2,
                                     trip_mid - 2, trip_mid + 1, trip_mid + 8)})
    cold = {T: r.run("cold", T) for T in pts}
    en = {T: r.run("en", T, IX_HOT, "0") for T in pts}

    diag_runs = [x["id"] for x in r.runs if x["solver_diagnostic"]]
    result = {
        "record_id": rec_id,
        "issue": 230,
        "corner": {"process": PROCESS, "supply_v": VSUP, "note": "single corner; NOT PVT qualification"},
        "bisection_tol_c": args.tol,
        "t_reset_falling_c": {"bracket": [reset_lo, reset_hi], "midpoint": reset_mid,
                              "def": "lowest T at which the tripped state is still held"},
        "t_trip_rising_c": {"bracket": [trip_lo, trip_hi], "midpoint": trip_mid,
                            "def": "highest T at which the untripped state is still held"},
        "hysteresis_c": {
            "midpoint": trip_mid - reset_mid,
            "min": trip_lo - reset_hi, "max": trip_hi - reset_lo,
            "grid_resolution_c": 2.0,
            "exceeds_grid_resolution": (trip_lo - reset_hi) > 2.0,
        },
        "amplitude_robustness": robust,
        "cold_start_by_temp": {str(T): {"tripped": x["cold_start_tripped"], "sns_minus_ref_mv": x["sns_minus_ref_mv_at_hold"]}
                               for T, x in cold.items()},
        "en_reenable_from_tripped_by_temp": {
            str(T): {"tripped_before_dip": x["hold_tripped"], "ts_cmp_while_en_low_v": x["ts_cmp_while_en_low_v"],
                     "en_while_low_v": x["en_while_low_v"], "tripped_after_reenable": x["after_en_reenable_tripped"]}
            for T, x in en.items()},
        "n_runs": len(r.runs),
        "runs_with_solver_diagnostic": diag_runs,
        "xschem_expr_substitutions": n_expr,
        "nodeset_card_dropped_for_tran_uic": True,
        "runs": r.runs,
        "tools": cr.tool_versions(),
        "pdk": {"variant": pdk.variant, "installed_commit": pdk.installed_commit,
                "pinned_commit": pdk.pin["open_pdks_commit"], "lib": str(pdk.lib_file)},
        "repo": git,
        "command": "python3 sim/thermal/run_hysteresis.py" + (f" --tag {args.tag}" if args.tag else ""),
        "timestamp": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
    }
    (out / "result.json").write_text(json.dumps(result, indent=2) + "\n")
    h = result["hysteresis_c"]
    print(f"T_reset(falling) = {reset_mid:.3f} C [{reset_lo:g},{reset_hi:g}]")
    print(f"T_trip(rising)   = {trip_mid:.3f} C [{trip_lo:g},{trip_hi:g}]")
    print(f"hysteresis = {h['midpoint']:.3f} C (min {h['min']:.3f}, max {h['max']:.3f}); solver-diagnostic runs: {diag_runs}")
    shutil.rmtree(r.work, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
